FROM {{base_image}}

ENV VNC_PORT=5900 \
    NOVNC_PORT=6080 \
    NOVNC_HOME=/srv/noVNC \
    GET_HOST="ip route | awk '/default/ { print \$3 }'"

RUN apk update && apk add --no-cache git python3 procps && \
    mkdir -p $NOVNC_HOME && \
    wget -qO- https://github.com/novnc/noVNC/archive/v1.2.0.tar.gz | tar xz --strip 1 -C $NOVNC_HOME && \
    chmod +x $NOVNC_HOME/utils/*.sh

EXPOSE $NOVNC_PORT

CMD HOST_IP=$(eval $GET_HOST);$NOVNC_HOME/utils/launch.sh --vnc $HOST_IP:$VNC_PORT
